### ISSUE TITLE
Fonts aren't loading for me

### ISSUE THREAD

**Issue by sohlis** [davidchambers/davidchambers.me#1]
`Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by davidchambers** [comment]
Thanks for the heads-up, @sohlis. I stopped paying my Typekit subscription as I haven't been making enough use of it to warrant the cost. I'll switch to Georgia for now.

**Comment by sohlis** [comment]
`<link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet' type='text/css'>`
googles garamond isnt bad (and free!)
